#!/usr/bin/env groovy

pipeline{

    environment{
        repoUrl = 'https://PeFerreira98@bitbucket.org/mei-isep/odsoft-18-19-ifp-g114.git'

        //service (personal)
        //credentials = '478a9f2c-5b0a-4b9f-a7ee-4d306dc84a8c'

        //docker container (personal)
        //credentials = '2bbcefc9-6456-457f-89c7-5737e29a309c'
        
        //docker container (work)
        credentials = 'bitB'
    }

    agent any

    stages{

        stage("GitCheckout"){
            steps{
                echo 'Checkout..'
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: "${credentials}", url: "${repoUrl}"]]])  
            }
        }
        
        stage('Clean'){
            steps{
                echo 'Cleaning..'
                dir('odsoft/exercise2/component1/cms/'){
                    script{
                        if (isUnix()) sh './gradlew clean --info'
                        else bat 'gradlew clean --info'                        
                    }
                }                
            }
        }
            
        stage('Build'){
            steps{
                echo 'Building..'
                dir('odsoft/exercise2/component1/cms/'){
                    script{
                        if (isUnix()) sh './gradlew build --info'
                        else bat 'gradlew build --info'
                    }
                }
            }			
        }
        
        stage('Unit Tests'){
            steps{
                echo 'Unit Testing..'
                dir('odsoft/exercise2/component1/cms/'){
                    script{
                        if (isUnix()) sh './gradlew cleanTest test --info'
                        else bat 'gradlew cleanTest test --info'
                    }
                }
            }	
        }
        
        stage('Integration Tests'){
            steps{
                echo 'Integration Testing..'
                dir('odsoft/exercise2/component1/cms/'){
                    script{
                        if (isUnix()) sh './gradlew integrationTest --info'
                        else bat 'gradlew integrationTest --info'
                    }
                }
            }	
        }
        
        stage('Javadoc Generation'){
            steps{
                echo 'Generating Javadoc..'
                dir('odsoft/exercise2/component1/cms/'){
                    script{
                        if (isUnix()) sh './gradlew javadoc --info'
                        else bat 'gradlew javadoc --info'
                    }
                }
            }	
        }
        
        stage('Archiving Artifacts'){
            steps{
                echo 'Archiving Artefacts..'
            }
        }

        stage('Test Publish'){
            steps{
                echo 'Publishing Tests..'
            }
        }

        stage('Javadoc Publish'){
            steps{
                echo 'Publishing Javadoc..'
            }
        }

        stage('Jacoco Publish'){
            steps{
                echo 'Publishing Jacoco test coverage..'
            }
        }

        stage('Deploy'){
            steps{
                echo 'Deploy App..'
                //dir('odsoft/exercise2/component1/cms/'){
                //    script{
                //        
                //    }
                //}
            }
        }
    }
}