node {
    stage("GitCheckout"){            
        echo 'Checkout..'
        //docker
        //checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '2bbcefc9-6456-457f-89c7-5737e29a309c', url: 'https://PeFerreira98@bitbucket.org/mei-isep/odsoft-18-19-ifp-g114.git']]])
        //service
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '478a9f2c-5b0a-4b9f-a7ee-4d306dc84a8c', url: 'https://PeFerreira98@bitbucket.org/mei-isep/odsoft-18-19-ifp-g114.git']]])
    }
	
	stage('Clean'){
        echo 'Cleaning..'
        dir('odsoft/exercise2/component1/cms/'){
            if (isUnix()) sh './gradlew clean --info'
            else bat 'gradlew clean --info'
        }
    }
		
    stage('Build'){
        echo 'Building..'
        dir('odsoft/exercise2/component1/cms/'){
            if (isUnix()) sh './gradlew build --info'
            else bat 'gradlew build --info'
        }			
    }
	
    stage('Tests'){
        echo 'Unit Testing..'
        dir('odsoft/exercise2/component1/cms/'){
            if (isUnix()) sh './gradlew cleanTest test --info'
            else bat 'gradlew cleanTest test --info'
        }	

        echo 'Integration Testing..'
        dir('odsoft/exercise2/component1/cms/'){
            if (isUnix()) sh './gradlew integrationTest --info'
            else bat 'gradlew integrationTest --info'
        }	
    }
	
	stage('Artifacts'){
        echo 'Generating Javadoc..'
        dir('odsoft/exercise2/component1/cms/'){
            if (isUnix()) sh './gradlew javadoc --info'
            else bat 'gradlew javadoc --info'
        }	

        echo 'Archiving Artefacts..'
    }

    stage('Publish'){
        echo 'Publishing Tests..'
        echo 'Publishing Javadoc..'
        echo 'Publishing Jacoco test coverage..'
    }

    stage('Deploy'){
        echo 'Deploy App..'
    }
	
}