@startuml updateContact-SD.png

unknown -> ContactsServiceImpl: getContact(Id)

unknown -> ContactsServiceImpl: updateContact(contact)

ContactsServiceImpl -> ContactsServiceImpl: contacts.remove(Id)
ContactsServiceImpl -> ContactsServiceImpl: contacts.put(contact)

unknown <-- ContactsServiceImpl: contact

@enduml