version: '3.7'
services:

  h2.db: #Check https://hub.docker.com/r/oscarfonts/h2/ for details
    image: oscarfonts/h2
    ports:
      - 8889:81
      - 8890:1521

  cms:
    build: 
      context: ./cms.1
      dockerfile: Dockerfile
    ports:
      - 8888:8080
    depends_on:
      - h2.db

  