version: '3.7'
services:

  h2.db:
    image: oscarfonts/h2
    ports:
      - 8889:81

#  sql.db:
#    image: mcr.microsoft.com/mssql/server
#    ports:
#      - 8890:1433

  cms:
    build: 
      context: ./cms
      dockerfile: Dockerfile
    ports:
      - 8888:8080
    depends_on:
      - h2.db

  