#!/usr/bin/env groovy

pipeline
{
    environment
    {
        // Repository
        // repoUser must be defined as a global variable in jenkins
        credentials = 'BitbucketAuth'
        repository = 'bitbucket.org/mei-isep/odsoft-18-19-ifp-g114.git'
        repoUrl = "https://${repoUser}@${repository}"

        // Dirs
        projectDir = 'project/cms/'

        // .War and services
        cmsWar = 'cmsproject'

        // Web URLs, Ports and stuff
        tomcatPort = '8888'
		tomcatUrl = "http://localhost:${tomcatPort}"
		cmsUrl = "${tomcatUrl}/${cmsWar}/"

        // Discord Webhook for some fancy stuff
        discordWebHook = 'https://discordapp.com/api/webhooks/514846042005569537/yWTNJnwN-pdceFvll4LofJ1ihg4BDho8Vg_g27DaU_jipQWjld8endZ_3CbzJcqVN9fo'
        startTime = new Date().format('dd/MM/yyyy HH:mm:ss')
    }
    
    agent any

    stages
    {
        stage("Git Checkout")
        {
            steps
            {
                echo 'Checkout..'
                //checkout([$class: 'GitSCM', branches: [[name: '*/develop']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: "${credentials}", url: "${repoUrl}"]]])
                checkout scm
            }
        }
        
        stage('Preparation')
        {
            steps 
            {
                dir("${projectDir}")
                {
                    script
                    {
                        if (isUnix()) sh './gradlew.sh cleanTest cleanIntegrationTest cleanJacocoTestReport cleanJacocoIntegrationReport cleanPitest cleanCheckstyleMain cleanCheckstyleTest cleanFindbugsMain cleanFindbugsTest'
                        else bat 'gradlew.bat cleanTest cleanIntegrationTest cleanJacocoTestReport cleanJacocoIntegrationReport cleanPitest cleanCheckstyleMain cleanCheckstyleTest cleanFindbugsMain cleanFindbugsTest'
                    }
                }                
            }
        }
            
        stage('Build')
        {
            steps
            {
                echo 'Building..'
                dir("${projectDir}")
                {
                    script
                    {
                        if (isUnix()) sh './gradlew build'
                        else bat 'gradlew build'
                    }
                }
            }
        }

        stage("Archive Artifacts + Javadoc + Code quality reports")
        {
            parallel
            {
                stage('Javadoc')
                {
                    steps
                    {
                        echo 'Generating Javadoc..'
                        dir("${projectDir}")
                        {
                            script
                            {
                                if (isUnix()) sh './gradlew javadoc'
                                else bat 'gradlew javadoc'
                            }

                            step([$class: 'JavadocArchiver', javadocDir: "build/docs/javadoc", keepAll: false])
                        }
                    }	
                }
                
                stage('Archiving Artifacts')
                {
                    steps
                    {
                        echo 'Archiving Artefacts..'
                        archiveArtifacts artifacts: "${projectDir}/build/libs/*.war", fingerprint: true, onlyIfSuccessful: true
                    }
                }

                stage('Code Quality Report - Checkstyle')
                {
                    steps
                    {
                        dir("${projectDir}")
                        {
                            script
                            {
                                if (isUnix()) sh './gradlew checkstyleMain checkstyleTest'
                                else bat 'gradlew checkstyleMain checkstyleTest'
                            }

                            checkstyle canComputeNew: false, defaultEncoding: '', failedTotalAll: '300', healthy: '30', pattern: 'build/reports/checkstyle/*.xml', unHealthy: '15', unstableTotalAll: '500'
                        }
                    }
                }

                stage('Code Quality Report - Findbugs')
                {
                    steps
                    {
                        dir("${projectDir}")
                        {
                            script
                            {
                                if (isUnix()) sh './gradlew findbugsMain findbugsTest'
                                else bat 'gradlew findbugsMain findbugsTest'
                            }

                            findbugs canComputeNew: false, defaultEncoding: '', excludePattern: '', failedTotalAll: '25', healthy: '30', includePattern: '', pattern: 'build/reports/findbugs/*.xml', unHealthy: '15', unstableTotalAll: '50'
                        }
                    }
                }
            }
        }

        stage("Test Preparation")
        {
            steps
            {
                dir("${projectDir}")
                {
                    script
                    {
                        if (isUnix()) sh 'docker run -d -p 8890:1521 -p 8889:81 --name=H2TestDB oscarfonts/h2'
                        else bat 'docker run -d -p 8890:1521 -p 8889:81 --name=H2TestDB oscarfonts/h2'
                    }
                }
            }
        }

        stage("Tests")
        {
            parallel
            {
                stage('Unit Tests')
                {
                    steps
                    {
                        echo 'Unit Testing..'
                        dir("${projectDir}")
                        {
                            script
                            {
                                if (isUnix()) sh './gradlew test jacocoTestReport'
                                else bat 'gradlew test jacocoTestReport'
                            }

                            junit allowEmptyResults: false, testResults: "build/test-results/test/*.xml"
                            //jacoco classPattern: "build/classes", exclusionPattern: '**/*Test*.class', execPattern: "build/jacoco/test.exec", sourceExclusionPattern: '**/*Test*.java', sourcePattern: "src/main/java"
                            jacoco buildOverBuild: true, changeBuildStatus: true, classPattern: 'build/classes', deltaBranchCoverage: '15', deltaClassCoverage: '15', deltaComplexityCoverage: '15', deltaLineCoverage: '15', deltaMethodCoverage: '15', exclusionPattern: '**/*Test*.class,**/client/', execPattern: 'build/jacoco/test.exec', inclusionPattern: '**/*.class', maximumBranchCoverage: '10', maximumClassCoverage: '10', maximumComplexityCoverage: '10', maximumInstructionCoverage: '10', maximumLineCoverage: '10', maximumMethodCoverage: '10', minimumBranchCoverage: '10', minimumClassCoverage: '10', minimumComplexityCoverage: '10', minimumInstructionCoverage: '10', minimumLineCoverage: '10', minimumMethodCoverage: '10', sourceExclusionPattern: '**/*Test*.java,**/client/', sourcePattern: 'src/main/java'
                        }
                    }	
                }
                
                stage('Integration Tests')
                {
                    steps
                    {
                        echo 'Integration Testing..'
                        dir("${projectDir}")
                        {
                            script
                            {
                                if (isUnix()) sh './gradlew integrationTest jacocoIntegrationReport'
                                else bat 'gradlew integrationTest jacocoIntegrationReport'
                            }

                            junit allowEmptyResults: false, testResults: "build/test-results/integrationTest/*.xml"
                            //jacoco classPattern: "build/classes", exclusionPattern: '**/*Test*.class', execPattern: "build/jacoco/integrationTest.exec", sourceExclusionPattern: '**/*Test*.java', sourcePattern: "src/main/java"
                            jacoco buildOverBuild: true, changeBuildStatus: true, classPattern: 'build/classes', deltaBranchCoverage: '15', deltaClassCoverage: '15', deltaComplexityCoverage: '15', deltaLineCoverage: '15', deltaMethodCoverage: '15', exclusionPattern: '**/*Test*.class,**/client/', execPattern: 'build/jacoco/integrationTest.exec', inclusionPattern: '**/*.class', maximumBranchCoverage: '10', maximumClassCoverage: '10', maximumComplexityCoverage: '10', maximumInstructionCoverage: '10', maximumLineCoverage: '10', maximumMethodCoverage: '10', minimumBranchCoverage: '10', minimumClassCoverage: '10', minimumComplexityCoverage: '10', minimumInstructionCoverage: '10', minimumLineCoverage: '10', minimumMethodCoverage: '10', sourceExclusionPattern: '**/*Test*.java,**/client/', sourcePattern: 'src/main/java'
                        }
                    }	
                }

                stage('Mutation Tests')
                {
                    steps
                    {
                        echo 'Mutation Testing..'
                        dir("${projectDir}")
                        {
                            script
                            {
                                try {
                                    if (isUnix()) sh './gradlew pitest'
                                    else bat 'gradlew pitest'
                                } 
                                catch(eTestMutation) 
                                {
                                    echo 'Exception caught while processing Mutatuion Tests'
                                    currentBuild.result = 'SUCCESS'
                                }
                            }
                            
                            publishHTML([allowMissing: true, alwaysLinkToLastBuild: false, keepAll: false, reportDir: "build/reports/pitest", reportFiles: 'index.html', reportName: 'Mutation Report', reportTitles: 'Mutation Report'])
                        }
                    }	
                }
            }
        }

        stage('Deploy for Testing')
        {
            steps
            {
                echo 'Deploy App..'
                dir("${projectDir}")
                {
                    script
                    {
                        if (isUnix())
                        {
                        	sh 'docker stop H2TestDB'
                            sh 'docker rm -f H2TestDB'
                        
                            sh 'cd .. && docker-compose up -d --build'
                        }
                        else
                        {
                        	bat 'docker stop H2TestDB'
                            bat 'docker rm -f H2TestDB'
                            
                            bat 'cd .. && docker-compose up -d --build'
                        }
                    }
                }
            }
        }

        stage('System Smoke Tests')
        {
            options{ retry(5) }
            
            steps
            {
                echo 'System Testing..'
                sleep(5)

                dir("${projectDir}")
                {
                    script
                    {
                        if (isUnix()) sh "curl ${cmsUrl}"
                        else powershell "Invoke-RestMethod -Uri ${cmsUrl}"
                    }
                }                
            }
        }

        stage('Manual UI Acceptance Tests')
        {
            options{ timeout(time: 1, unit: 'HOURS') }
            steps
            {
                mail (to: '1140953@isep.ipp.pt 1141233@isep.ipp.pt', 
                    subject: "Manual Tests", 
                    body: "Please do some testing and approve the build on jenkins. CHOP CHOP! Get to work!")

                //input 'Please Approve or fail the build after UI Acceptance Tests'
                
                dir("${projectDir}")
                {
                    script
                    {
                        if (isUnix()) sh 'cd .. && docker-compose down --rmi local'
                        else bat 'cd .. && docker-compose down --rmi local'
                    }
                }
            }
        }

        stage('Deploy Release')
        {
            when { branch '*release/*' }

            steps
            {
                echo 'Deploy App in Release Environment..'
                dir("${projectDir}")
                {
                    script
                    {
                        if (isUnix()) sh './gradlew deploy --info && %CATALINA_HOME%/bin/startup.sh'
                        else bat 'gradlew deploy --info && %CATALINA_HOME%/bin/startup.bat'
                    }
                }
            }
        }
    }

    post
    {
        success
        {
            echo 'Creating PDF report..'
            dir("${projectDir}")
            {
                script 
                {
                    if (isUnix()) sh './gradlew pdf'
                    else bat 'gradlew pdf'
                    archiveArtifacts allowEmptyArchive: false, artifacts: "**/*.pdf", fingerprint: true, onlyIfSuccessful: true
                }

            }
            
            dir('project/')
            {
                echo 'Ziping artfacts..'
                zip archive: true, glob: 'cms/build/reports/relatory/*.pdf,cms/Jenkinsfile,cms/build.gradle,cms/Dockerfile,docker-compose.yml,cms/build/libs/*.war,cms/build/docs/javadoc,report.md', zipFile: 'ODSOFT_M1D_1140953_1141233.zip'
            
                echo 'Deleting ZIP..'
                script
                {
                    if (isUnix()) sh "rm ./ODSOFT_M1D_1140953_1141233.zip"
                    else  bat "del ./ODSOFT_M1D_1140953_1141233.zip"
                }
            }
        }
        
        failure
        {
            dir("${projectDir}")
            {
                script
                {
                    try
                    {
                        if (isUnix())
                        {
                            sh 'docker stop H2TestDB'
                            sh 'docker rm -f H2TestDB'
                        }
                        else
                        {
                            bat 'docker stop H2TestDB'
                            bat 'docker rm -f H2TestDB'
                        }
                    }
                    catch (Exception e)
                    {
                        echo 'docker was already stopped'
                    }
                    
                    try
                    {
                        if (isUnix()) sh 'cd .. && docker-compose down --rmi local'
                        else bat 'cd .. && docker-compose down --rmi local'
                    }
                    catch (Exception e)
                    {
                        echo 'docker was already stopped'
                    }
                }
            }
        }

        always
        {
            bitbucketStatusNotify(buildState: currentBuild.currentResult)

            discordSend description: "Finished: ${BUILD_TAG}\nBuild Status: ${currentBuild.currentResult}\nStart Build Time: ${startTime}\nFinish Build Time: ${new Date().format('dd/MM/yyyy HH:mm:ss')}", result: currentBuild.currentResult, webhookURL: "${discordWebHook}"
        }
    }
}