@startuml viewContact-SD.png

actor User
participant ContactsApp
participant ContactsController
participant ContactsPresenter
participant ContactsService


User ->> ContactsApp : "view contact"

ContactsApp -> ContactsController : go()

create ContactsPresenter
ContactsController -> ContactsPresenter: new
ContactsController -> ContactsPresenter: go()

ContactsPresenter -> ContactsPresenter: fetchContactDetails()

ContactsPresenter -> ContactsServiceAsync: getContactDetails()

ContactsPresenter -> ContactsPresenter: sortContactDetails()

ContactsPresenter -> Display: setData()

User <-- Display: "show contacts"


@enduml
